-- Bulk import of the internal pricing matrix v5 (Aug 2026): 10 tiers
-- from Be Found ($650/mo) to Pro ($4,500/mo), each with its full deliverable
-- set, plus 4 a la carte add-ons. Visibility and Dominance already existed
-- in the catalog — this corrects Visibility's stale $2,000 price to the
-- matrix's real $2,500 and refreshes both packages' deliverable data to
-- match exactly, rather than leaving them out of sync with the 8 new tiers.
-- This is a documentation-only record of a live data change applied via the
-- Supabase MCP service-role client (this project has no migration runner).
-- Not idempotent — re-running would duplicate rows, matching the existing
-- precedent set by migrations 0002/0010/0012.

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Be Found', 650, 'The essential starting point — technical health, one optimized page, and a first guest post placement.', '', '[{"value":"0","label":"High-DR Link Inserts"},{"value":"0","label":"AI Citation Listicles"},{"value":"1","label":"Guest Posts DA 30+"},{"value":"1","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — 1 page","Aggregator submission","Directory citations — 3–4 / month"]},{"group_label":"Reporting & Strategy","items":["24/7 reporting dashboard"]}]'::jsonb, '[{"title":"1 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"3–4 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"1 Pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 0, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Be Found Plus', 850, 'A step up from Be Found, with a second page optimized and two guest posts a month.', '', '[{"value":"0","label":"High-DR Link Inserts"},{"value":"0","label":"AI Citation Listicles"},{"value":"2","label":"Guest Posts DA 30+"},{"value":"2","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — 2 pages","Aggregator submission","Directory citations — 3–4 / month"]},{"group_label":"Reporting & Strategy","items":["24/7 reporting dashboard"]}]'::jsonb, '[{"title":"2 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"3–4 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"2 Pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 1, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Entry', 1000, 'Your first authority placements begin here, alongside broader technical coverage.', '', '[{"value":"1","label":"High-DR Link Inserts"},{"value":"1","label":"AI Citation Listicles"},{"value":"1","label":"Guest Posts DA 30+"},{"value":"3","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 3 pages","Aggregator submission","Directory citations — 3–4 / month"]},{"group_label":"Reporting & Strategy","items":["24/7 reporting dashboard"]}]'::jsonb, '[{"title":"3 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"3–4 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"Top 3 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 2, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Entry Plus', 1500, 'GBP optimization and management joins the mix, with more directory citations and a bigger authority footprint.', '', '[{"value":"1","label":"High-DR Link Inserts"},{"value":"1","label":"AI Citation Listicles"},{"value":"2","label":"Guest Posts DA 30+"},{"value":"4","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 3 pages","Aggregator submission","Directory citations — 4–5 / month","GBP optimization & management"]},{"group_label":"SOURCE™ & Content","items":["SOURCE™ research asset — 1 / year"]},{"group_label":"Reporting & Strategy","items":["24/7 reporting dashboard"]}]'::jsonb, '[{"title":"4 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"4–5 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"1 SOURCE™ Research Asset / year","description":"Original research that builds topical authority for AI citation"},{"title":"Top 3 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 3, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Growth', 2000, 'Schema, AI citation tracking, and monthly strategy calls begin here — the first fully-reported tier.', '', '[{"value":"2","label":"High-DR Link Inserts"},{"value":"2","label":"AI Citation Listicles"},{"value":"2","label":"Guest Posts DA 30+"},{"value":"6","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 4 pages","Aggregator submission","Directory citations — 5–6 / month","GBP optimization & management","Schema implementation — Q1 setup"]},{"group_label":"SOURCE™ & Content","items":["SOURCE™ research asset — 1 / year","Long form blogs — 6 / year"]},{"group_label":"Reporting & Strategy","items":["AI mention & citation tracking","24/7 reporting dashboard","Monthly strategy call"]}]'::jsonb, '[{"title":"6 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"5–6 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"1 SOURCE™ Research Asset / year","description":"Original research that builds topical authority for AI citation"},{"title":"Top 4 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 4, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Visibility', 2500, 'The complete five-channel foundation. Everything you need to establish authority across all five discovery channels.', '', '[{"value":"2","label":"High-DR Link Inserts"},{"value":"2","label":"AI Citation Listicles"},{"value":"3","label":"Guest Posts DA 30+"},{"value":"7","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 4 pages","Aggregator submission","Directory citations — 6–7 / month","GBP optimization & management","Schema implementation — Q1 setup"]},{"group_label":"SOURCE™ & Content","items":["SOURCE™ research asset — 2 / year","Long form blogs — 6 / year"]},{"group_label":"Reporting & Strategy","items":["AI mention & citation tracking","24/7 reporting dashboard","Monthly strategy call"]}]'::jsonb, '[{"title":"7 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"6–7 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"2 SOURCE™ Research Assets / year","description":"Original research that builds topical authority for AI citation"},{"title":"Top 4 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 5, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Momentum', 3000, 'Ongoing schema implementation and a larger authority stack for markets that need to move faster.', '', '[{"value":"3","label":"High-DR Link Inserts"},{"value":"2","label":"AI Citation Listicles"},{"value":"3","label":"Guest Posts DA 30+"},{"value":"8","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 5 pages","Aggregator submission","Directory citations — 6–7 / month","GBP optimization & management","Schema implementation — Ongoing"]},{"group_label":"SOURCE™ & Content","items":["SOURCE™ research asset — 2 / year","Long form blogs — 1 / month"]},{"group_label":"Reporting & Strategy","items":["AI mention & citation tracking","24/7 reporting dashboard","Monthly strategy call"]}]'::jsonb, '[{"title":"8 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"6–7 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"2 SOURCE™ Research Assets / year","description":"Original research that builds topical authority for AI citation"},{"title":"Top 5 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 6, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Authority', 3500, 'Quarterly SOURCE™ research and monthly long-form content, with higher-authority guest post placements.', '', '[{"value":"3","label":"High-DR Link Inserts"},{"value":"3","label":"AI Citation Listicles"},{"value":"4","label":"Guest Posts DA 40+"},{"value":"10","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 5 pages","Aggregator submission","Directory citations — 6–7 / month","GBP optimization & management","Schema implementation — Ongoing"]},{"group_label":"SOURCE™ & Content","items":["SOURCE™ research asset — 3 / year","Long form blogs — 1 / month"]},{"group_label":"Reporting & Strategy","items":["AI mention & citation tracking","24/7 reporting dashboard","Monthly strategy call"]}]'::jsonb, '[{"title":"10 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"6–7 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"3 SOURCE™ Research Assets / year","description":"Original research that builds topical authority for AI citation"},{"title":"Top 5 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 7, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Dominance', 4000, 'For markets where second place isn''t an option. Nearly double the authority placements, higher DA targets, ongoing schema, and quarterly SOURCE™ research.', 'Most Popular', '[{"value":"4","label":"High-DR Link Inserts"},{"value":"3","label":"AI Citation Listicles"},{"value":"4","label":"Guest Posts DA 40+"},{"value":"11","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 6 pages","Aggregator submission","Directory citations — 6–7 / month","GBP optimization & management","Schema implementation — Ongoing"]},{"group_label":"SOURCE™ & Content","items":["SOURCE™ research asset — 4 / year","Long form blogs — 1 / month"]},{"group_label":"Reporting & Strategy","items":["AI mention & citation tracking","24/7 reporting dashboard","Monthly strategy call"]}]'::jsonb, '[{"title":"11 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"6–7 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"4 SOURCE™ Research Assets / year","description":"Original research that builds topical authority for AI citation"},{"title":"Top 6 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 8, true);

insert into service_packages (name, monthly_price, tagline, badge_label, stat_callouts, feature_groups, monthly_deliverables, sort_order, active)
values ('Pro', 4500, 'Our most aggressive tier — five guest posts, six SOURCE™ research assets a year, and premium DA 50+ placements.', '', '[{"value":"5","label":"High-DR Link Inserts"},{"value":"4","label":"AI Citation Listicles"},{"value":"5","label":"Guest Posts DA 50+"},{"value":"14","label":"Total placements/mo"}]'::jsonb, '[{"group_label":"Foundation","items":["Technical SEO & site health monitoring","In-depth page optimizations — Top 7 pages","Aggregator submission","Directory citations — 6–7 / month","GBP optimization & management","Schema implementation — Ongoing"]},{"group_label":"SOURCE™ & Content","items":["SOURCE™ research asset — 6 / year","Long form blogs — 2 / month"]},{"group_label":"Reporting & Strategy","items":["AI mention & citation tracking","24/7 reporting dashboard","Monthly strategy call"]}]'::jsonb, '[{"title":"14 Guest Post / AI Citation Placements / mo","description":"High-authority links + AI brand mentions combined"},{"title":"6–7 NAP Citations / month","description":"Consistent business info across every major directory"},{"title":"6 SOURCE™ Research Assets / year","description":"Original research that builds topical authority for AI citation"},{"title":"Top 7 pages Optimized","description":"Bringing key service pages up to a 95 optimization score"}]'::jsonb, 9, true);

insert into addon_items (name, description, price_amount, price_unit, category, sort_order, active)
values ('Aggregator Submissions', 'Annual submission to major business aggregators and directories.', 100, '/year', 'addon', 20, true);

insert into addon_items (name, description, price_amount, price_unit, category, sort_order, active)
values ('Directory / Citation Distribution', 'Ongoing directory and citation distribution beyond the plan''s included volume.', 100, '/mo', 'addon', 21, true);

insert into addon_items (name, description, price_amount, price_unit, category, sort_order, active)
values ('Local Visibility Boost', 'Extra local SEO push — GBP optimization, local citations, and Maps signals.', 150, '/mo', 'addon', 22, true);

insert into addon_items (name, description, price_amount, price_unit, category, sort_order, active)
values ('One-Time Page Optimization', 'A full in-depth optimization of one additional page beyond the plan''s included pages.', 250, '/page', 'addon', 23, true);

